const appRoutes = {
    ROUTE_HOME: '/',
    ROUTE_ADMINS: '/admins',
    ROUTE_USERS: '/users',
    ROUTE_SPECIALITIES: '/specialities',
    ROUTE_PATIENTS: '/patients',
    ROUTE_NURSES: '/nurses',
    ROUTE_ANALYSTS: '/analysts',
    ROUTE_DOCTORS: '/doctors',
    ROUTE_LOGIN: '/login',
    ROUTE_NOT_FOUND: '/_error',
}
const apiRoutes = {
    GET_PATIENTS: '/nucleus-personnel/patients',
    GET_ADMINS: '/user-consultation/users/admins',
    USERS: '/user-consultation/users',
    PATIENTS: '/nucleus-personnel/patients',
    DOCTORS: '/nucleus-personnel/doctors',
    NURSES: '/nucleus-personnel/nurses',
    CONSULTATIONS: '/user-consultation/consultations',
    MEDICAL_CARES: '/medical-cares',
    OBSERVATIONS: '/user-consultation/consultations/observations',
    HOSPITALS: '/system-nucleus/hospitals',
    DIAGNOSIS: '/user-consultation/consultations/diagnosis',
    SYMPTOMS: '/user-consultation/consultations/symptoms',
    PRESCRIPTIONS: '/user-consultation/consultations/prescriptions',
    GET_ANALYSTS: '/system-nucleus/analysts',
    GET_DOCTORS: '/nucleus-personnel/doctors',
    GET_NURSES: '/nucleus-personnel/nurses',
    GET_SPECIALITIES: '/specialities',
    GET_AUTHORITIES: '/user-consultation/users/authorities',
    GET_CURRENT_USER: '/user-consultation/users/account',
    GET_DOCTOR: (id) => `/nucleus-personnel/doctors/${id}`,
    GET_PATIENT: (id) => `/nucleus-personnel/patients/${id}`,
    GET_OBSERVATION: (id) => `/user-consultation/observations/${id}`,
    GET_NURSE: (id) => `/nucleus-personnel/nurses/${id}`,
    GET_ANALYST: (id) => `/system-nucleus/analysts/${id}`,
    GET_USER: (id) => `/user-consultation/users/${id}`,
    LOGIN: '/user-consultation/users/login',
    GET_USER_AVATAR: (uuid) => `${process.env.NEXT_PUBLIC_API_URL}/files/${uuid}`,
    MEDICAL_CARES_LIST: '/medical-cares-list',
}
const userRoles = {
    ROLE_PATIENT: 'ROLE_PATIENT',
    ROLE_NURSE: 'ROLE_NURSE',
    ROLE_ANALYST: 'ROLE_ANALYST',
    ROLE_DOCTOR: 'ROLE_DOCTOR',
    ROLE_ADMIN_HOPSITAL: 'ROLE_ADMIN_HOSPITAL',
}
export {appRoutes, apiRoutes, userRoles}